Add missing preprocessor directives
STMicroelectronics/stm32f7xx_hal_driver pull request #4
Opened 2022-07-08 06:47 UTC by PhilippHaefele

As SPI6 is not available in some STMF7 derivatives, `__HAL_RCC_SPI6_CLK_ENABLE()` and `__HAL_RCC_SPI6_CLK_DISABLE()` need to be inside appropriate preprocessor directives

2022-09-27 10:57 UTC, RJMSTM commented
ST Internal Reference: 135503

2022-11-16 09:30 UTC, RJMSTM requested changes

2022-11-16 09:30 UTC, RJMSTM commented on Inc/stm32f7xx_hal_rcc_ex.h
> +#if defined (STM32F745xx) || (STM32F746xx) || defined (STM32F750xx) || defined (STM32F756xx) || defined (STM32F765xx) || defined (STM32F767xx) || defined (STM32F769xx) || defined (STM32F777xx) || def
> || (STM32F746xx) || 

should be `|| defined (STM32F746xx) || `

2022-11-17 08:04 UTC, closed without merging

2022-11-17 08:47 UTC, PhilippHaefele commented
@RJMSTM Sorry i somehow messed up this pull request and i can't reopen this one after i fixed the branch.

Therefore i opened https://github.com/STMicroelectronics/stm32f7xx_hal_driver/pull/5 which includes the fixes you requested